### ISSUE TITLE
Upgrade Mapbox GL

### ISSUE THREAD

**Issue by planemad** [publicmap/publicmap.github.io#6]
to v0.36 https://www.mapbox.com/mapbox-gl-js/api/

**Comment by SrihariThalla** [comment]
Do you mean updating [SDK JS](https://github.com/publicmap/publicmap.github.io/blob/master/package.json#L18) (which we are using at the moment) to [GL JS](https://github.com/mapbox/mapbox-gl-js/blob/master/package.json)?

**Comment by planemad** [comment]
Not sure about the difference between the two, but yes, GL JS is all we need.

**Comment by planemad** [comment]
Upgraded to 0.42
