### ISSUE TITLE
Add overpass querying

### ISSUE THREAD

**Issue by planemad** [publicmap/publicmap.github.io#7]
- Enter an [overpass query](http://overpass-turbo.eu) in a text box
- Query overpass and visualize results

**Comment by SrihariThalla** [comment]
Apart from rich info that the vector tiles can provide, what are the benefits over Overpass Turbo?

**Comment by planemad** [comment]
Nothing apart from the convenience of being able to query data from within this map instead of a seperate tool, was thinking later we could have certain preset categories that are interesting: trees, benches, streetlights.. and it would load and visualize the data on the map.

**Comment by 1ec5** [comment]
This is fixed now, right? 🎉

**Comment by planemad** [comment]
yeap!
